image: docker:latest
services:
  - name: docker:dind
    alias: docker


stages:          # List of stages for jobs, and their order of execution
  - build
  - test acceptation
  - Release image
  - deploy

docker-build:
  # Use the official docker image.
  stage: build
  script:
    - docker build -t mini-projet .
    - docker save mini-projet  >  mini-projet.tar
  artifacts:
    paths:
      -  mini-projet.tar    

test acceptation:
  # Official docker image.
  stage: test acceptation
  script:
    - docker load <  mini-projet.tar
    - docker run -d -p 80:80 --name static-website mini-projet 
    - sleep 5
    - apk --no-cache add curl
    - curl "http://docker:80"
    


release image:
  stage: Release image
  script:
    - docker load < mini-projet.tar
    - docker tag mini-projet "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker tag mini-projet "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
