image: docker:latest
services:
  - name: docker:dind
    alias: docker


stages:          # List of stages for jobs, and their order of execution
  - build
  - test acceptation
  - Release image
  - Deploy staging
  - Deploy prod

docker-build:
  # Use the official docker image.
  stage: build
  script:
    - docker build -t mini-projet .
    - docker save mini-projet  >  mini-projet.tar
  artifacts:
    paths:
      -  mini-projet.tar    

test acceptation:
  # Official docker image.
  stage: test acceptation
  script:
    - docker load <  mini-projet.tar
    - docker run -d -p 80:80 --name static-website mini-projet 
    - sleep 5
    - apk --no-cache add curl
    - curl "http://docker:80"
    


release image: 
  stage: Release image
  script:
    - docker load < mini-projet.tar
    - docker tag mini-projet "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker tag mini-projet "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"

deploy staging:
  stage: Deploy staging
  environment:
    name: staging
    url: https://eazytraining-staging-9839de32fe85.herokuapp.com # eg: url_a_recuperer_sur_heroku
  only:
    - master
  script:    
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku create alexzaza1-staging || echo "project already exist"
    - heroku container:push -a alexzaza1-staging web
    - heroku container:release -a alexzaza1-staging web 

deploy prod:
  stage: Deploy prod
  environment:
    name: prod
    url: https://alexzaza1-production-70584e6ff38a.herokuapp.com  # eg: url_a_recuperer_sur_heroku
  only:
    - master
  script:    
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku create alexzaza1-production || echo "project already exist"
    - heroku container:push -a alexzaza1-production web
    - heroku container:release -a alexzaza1-production web 
